services:
  postgres:
    image: postgres:18

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./backend/db/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  backend:
    build:
      context: ./backend

    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      SESSION_COOKIE_NAME: ${SESSION_COOKIE_NAME}
      SESSION_TTL: ${SESSION_TTL}
      SESSION_SECURE: ${SESSION_SECURE}

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "8080"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  frontend:
    build:
      context: ./frontend

    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:
