services:
  postgres:
    restart: unless-stopped

  backend:
    image: go-todo-backend:production
    build:
      target: production
    restart: unless-stopped

    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}

  frontend:
    image: go-todo-frontend:production
    build:
      target: production
    restart: unless-stopped

    ports:
      - "${PUBLIC_BIND_ADDRESS:-0.0.0.0}:${PUBLIC_PORT:-8080}:8080"
